"""Compile frozen weights to custom-ISA firmware and an integer oracle.

Generated program ROM contains weights and bias instructions, never target RGB.
Only two immediate instructions are parameterized by the pixel coordinate unit.
"""
from pathlib import Path
import json
import hashlib
import argparse

ROOT = Path(__file__).resolve().parents[1]


def infer(model, x, y):
    a = [x, y]
    for layer in model['layers']:
        result = []
        for weights, bias in zip(layer['weights'], layer['bias']):
            acc = bias
            for w, v in zip(weights, a):
                acc = max(-2147483648, min(2147483647, acc + w * v))
            result.append(max(0 if layer['relu'] else -128, min(127, acc >> layer['shift'])))
        a = result
    return a


def compile_model(model):
    program = [0, 0x20000000, 0, 0x20000001]
    mapping = [{'kind': 'coordinate', 'axis': 'x'}, {'kind': 'store', 'address': 0},
               {'kind': 'coordinate', 'axis': 'y'}, {'kind': 'store', 'address': 1}]
    input_addresses = [0, 1]

    def emit(word, **metadata):
        program.append(word); mapping.append(metadata)

    for li, layer in enumerate(model['layers']):
        outputs = []
        for ni, (weights, bias) in enumerate(zip(layer['weights'], layer['bias'])):
            assert -32768 <= bias <= 32767
            emit(bias & 0xffff, kind='bias', layer=li, neuron=ni)
            emit(0xC0000000, kind='seed', layer=li, neuron=ni)
            for wi, (weight, address) in enumerate(zip(weights, input_addresses)):
                assert -128 <= weight <= 127
                emit(0x90000000 | address, kind='activation', layer=li, neuron=ni, input=wi)
                emit(0x10000000 | (weight & 0xff), kind='weight', layer=li, neuron=ni, input=wi)
                emit(0xD0000000, kind='mac', layer=li, neuron=ni, input=wi)
            emit(0xE0000000 | (int(layer['relu']) << 8) | layer['shift'], kind='quantize', layer=li, neuron=ni)
            address = 240 + ni if li == len(model['layers']) - 1 else [16, 80][li] + ni
            emit(0x20000000 | address, kind='store', layer=li, neuron=ni, address=address)
            outputs.append(address)
        input_addresses = outputs
    emit(0x80000000 | (len(program)), kind='halt')
    assert len(program) < 65536
    return program, mapping


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--size', type=int, default=64)
    args = parser.parse_args(); size = args.size
    model_path = ROOT / 'neural/assets/model.json'
    model = json.loads(model_path.read_text())
    program, mapping = compile_model(model)
    generated = ROOT / 'neural/generated'; generated.mkdir(exist_ok=True)
    words = ',\n'.join(f'        {i} => x"{word:08X}"' for i, word in enumerate(program))
    package = f'''-- Generated by neural/export_program.py. Weights embedded as instructions.
library ieee;
use ieee.std_logic_1164.all;
package neural_program is
    constant IMAGE_SIZE : positive := {size};
    constant PROGRAM_LENGTH : positive := {len(program)};
    type program_t is array(0 to PROGRAM_LENGTH-1) of std_logic_vector(31 downto 0);
    constant PROGRAM_ROM : program_t := (\n{words});
end package;
'''
    (generated / 'neural_program.vhd').write_text(package)
    (generated / 'program-map.json').write_text(json.dumps(mapping, separators=(',', ':')))
    # Integer half-up coordinates, specified independently from training's grid.
    pixels = [infer(model, (x * 127 + (size - 1)//2)//(size - 1),
                    (y * 127 + (size - 1)//2)//(size - 1))
              for y in range(size) for x in range(size)]
    (generated / 'expected-rgb.txt').write_text(''.join(' '.join(map(str, p))+'\n' for p in pixels))
    (generated / 'manifest.json').write_text(json.dumps({
        'model_sha256': hashlib.sha256(model_path.read_bytes()).hexdigest(),
        'program_sha256': hashlib.sha256(package.encode()).hexdigest(),
        'image_size': size, 'instructions': len(program),
        'macs_per_pixel': sum(len(row) for layer in model['layers'] for row in layer['weights']),
        'pixel_count': len(pixels), 'status': 'reference-only; RTL verification required'
    }, indent=2)+'\n')
    print(f'Compiled {len(program)} instructions; {len(pixels)} reference pixels')


if __name__ == '__main__': main()
